const data = {
  products: [
    {
      name: 'Peanut X Kaws Shirt',
      slug: 'peanut-x-kaws-shirt',
      category: 'Shirts',
      image: '/images/p1.png',
      price: 25,
      countInStock: 0,
      brand: 'Uniqlo',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt from Uniqlo X Kaws collab',
    },
    {
      name: 'Peanut X Kaws Plushie',
      slug: 'peanut-x-kaws-plush',
      category: 'Plushies',
      image: '/images/p2.png',
      price: 45,
      countInStock: 10,
      brand: 'Uniqlo',
      rating: 4.7,
      numReviews: 15,
      description: 'High quality Uniqlo X Kaws plushie',
    },
    {
      name: 'Peanut X Kaws Sweater',
      slug: 'peanut-x-kaws-sweater',
      category: 'Sweater',
      image: '/images/p3.png',
      price: 80,
      countInStock: 10,
      brand: 'Uniqlo',
      rating: 3.8,
      numReviews: 25,
      description: 'High quality sweater from Uniqlo X Kaws collab',
    },
    {
      name: 'Peanut X Kaws Tote Bag',
      slug: 'peanut-x-kaws-tote-bag',
      category: 'Bags',
      image: '/images/p4.png',
      price: 15,
      countInStock: 20,
      brand: 'Uniqlo',
      rating: 5.0,
      numReviews: 3,
      description: 'Tote bag brought to you by Uniqlo X Kaws',
    },
  ],
};
export default data;
